makefile update

diff --git a/benchmarking/Makefile b/benchmarking/Makefile
--- a/benchmarking/Makefile
+++ b/benchmarking/Makefile
@@ -1,23 +1,57 @@
+.ONESHELL:
+SHELL := bash
+PYTHON := python
+PYTHONPATH := `pwd`
+
+# Directories
 ROOT := $(shell dirname $(realpath $(firstword ${MAKEFILE_LIST})))
 PARENT_ROOT := $(shell dirname ${ROOT})
 DATASET_DIR := data/fred
 
-.PHONY: help dataset model
-
 .DEFAULT_GOAL := help
 
+#* Help
+.PHONY: help
 help:
 	@echo "Available targets:"
 	@echo "  dataset           Download datasets to the data/fred/ directory."
 	@echo "  model repo=<name> Download a Hugging Face model to the local cache."
+	@echo "  install           Set up the Python virtual environment and install dependencies."
+	@echo "  format            Run code formatters (black, isort)."
 
+#* Installation
+.PHONY: install
+install:
+	@if ! type pipx &>/dev/null; then \
+		echo "pipx not found. Installing pipx..."; \
+		python -m pip install --user pipx; \
+		export PATH=$$PATH:$$HOME/.local/bin; \
+	fi
+	@if ! type uv &>/dev/null; then \
+		echo "uv not found. Installing uv..."; \
+		pipx install uv; \
+	fi
+	@echo "Setting up virtual environment..."
+	rm -rf .venv
+	python -m venv .venv
+	source .venv/bin/activate
+	type python
+	uv sync --lock --export > requirements.txt
+	uv sync
+	@echo "Environment setup complete."
+
+#* Datasets
+.PHONY: dataset
 dataset:
-	mkdir -p $(DATASET_DIR) && \
+	mkdir -p $(DATASET_DIR)
 	wget -O $(DATASET_DIR)/unemployment_counties.csv https://huggingface.co/datasets/yatsbm/FRED/resolve/main/unemployment/unemployment_counties.csv?download=true || \
-		{ echo "Error: Failed to download unemployment_counties.csv."; exit 1; } && \
+		{ echo "Error: Failed to download unemployment_counties.csv."; exit 1; }
 	wget -O $(DATASET_DIR)/unemployment_states.csv https://huggingface.co/datasets/yatsbm/FRED/resolve/main/unemployment/unemployment_states.csv?download=true || \
 		{ echo "Error: Failed to download unemployment_states.csv."; exit 1; }
+	@echo "Datasets downloaded successfully."
 
+#* Model Downloads
+.PHONY: model
 model:
 	@echo "Downloading model from Hugging Face repository: $(repo)"
 	@if [ -z "$(repo)" ]; then \
@@ -27,3 +61,12 @@ model:
 	@huggingface-cli download $(repo) --include "*.safetensors" --repo-type model || \
 		{ echo "Error: Failed to download model. Please check the repository name and your Hugging Face token."; exit 1; }
 	@echo "Model downloaded successfully to Hugging Face cache."
+
+#* Formatting
+.PHONY: format
+format:
+	@echo "Running code formatters..."
+	uv run pyupgrade --exit-zero-even-if-changed --py38-plus **/*.py
+	uv run isort --settings-path pyproject.toml ./
+	uv run black --config pyproject.toml ./
+	@echo "Code formatting complete."
